baseURL = 'https://cleanunicorn.github.io/'
languageCode = 'en-us'
theme = "terminal"
pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        inline = [['$', '$']]
        block = [['$$', '$$']]

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "about"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  autoCover = true

[languages]
  [languages.en]
    title = "Daniel Luca"
    languageName = "English"

    [languages.en.params]
      subtitle = "Security Researcher | Investor | Builder"
      owner = "Daniel Luca"
      menuMore = "Show more"
      readMore = "Read more"

      [languages.en.params.logo]
        logoText = "Daniel Luca"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "work"
        name = "Work"
        url = "/work/"
        weight = 20
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 30
